Detect SSH_AGENT_PID
FossilOrigin-Name: b398c7441961b4bf3358bf4ec5b3543c68b5735cfe7af16eaa80c09e6aec451b

diff --git a/bin/blom-sync b/bin/blom-sync
--- a/bin/blom-sync
+++ b/bin/blom-sync
@@ -1,19 +1,23 @@
 #!/usr/bin/env sh
 # vim : set filetype=sh
 
-# run as ssh-agent -t 300 bin/blom-sync
-ssh-add "$HOME/.ssh/axdev"
+if [ -z "$SSH_AGENT_PID" ]; then
+	echo "Error: run as 'ssh-agent -t 300 bin/blom-sync'. Exiting..."
+	exit 64
+fi
 
 if [ -z "$1" ]; then
 	echo "Error: no directory provided. Exiting..."
 	exit 64
 fi
 
-
 if [ -z "$2" ]; then
 	echo "Error: no article provided. Exiting..."
 	exit 64
 fi
+
+
+ssh-add "$HOME/.ssh/axdev"
 
 scp "$1/blom.db" blog:~/blog/blom.db
 
